# Generated by Django 3.2.5 on 2021-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0002_album_musician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', help_text='User Name not greater Than 200 character', max_length=200),
        ),
    ]
