# Generated by Django 3.2.5 on 2021-07-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Enter your Password'),
        ),
    ]
