# Generated by Django 3.2.5 on 2021-07-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0005_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('album_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pract.album')),
            ],
            bases=('pract.album',),
        ),
    ]
