# Generated by Django 3.2.5 on 2021-07-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0006_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(db_column='Musician First Name', max_length=50),
        ),
    ]
