# Generated by Django 3.2.5 on 2021-07-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0009_musician_numberofexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='numberOfExperience',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
