# Generated by Django 3.2.5 on 2021-08-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0010_alter_musician_numberofexperience'),
    ]

    operations = [
    ]
